services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.debug
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx-debug.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/static:/usr/share/nginx/html:ro
    networks:
      - debug-net
    depends_on:
      - hello_service

  hello_service:
    build:
      context: ./hello_service
      dockerfile: Dockerfile.debug
    hostname: hello_service
    environment:
      - HOME=/service
      - CCACHE_DIR=/service/.ccache
    security_opt:
      - seccomp=./hello_service/seccomp_config.json
    command:
      - ./run_as_user.sh
      - "${UID}"
      - "${GID}"
      - sh
      - -lc
      - "make build-debug && make test-debug && make start-debug"
    volumes:
      - ./hello_service:/service
    networks:
      - debug-net

networks:
  debug-net:
    driver: bridge

